### ISSUE TITLE
Cannot use 'netconf' (type *BootConf) as the type *netboot.NetConf

### ISSUE THREAD

**Issue by ouliuquan** [insomniacslk/exdhcp#1]
Hi, as the title error, is there any API forget to update, it seem that 
`"exdhcp\dhclient\main.go" line 65 and line 96`
has some parameter return type and nums error.

Glad that you check my issue.

**Comment by insomniacslk** [comment]
right, this repository is a bit left to itself, and I should probably merge the examples in the main library. I'll fix it for now and plan on merging the two repos

**Comment by insomniacslk** [comment]
done. Merge tracked at https://github.com/insomniacslk/dhcp/issues/415
